# coding: utf-8

"""
    Python API wrapper for Jellyfish Media Server

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from jellyfish.openapi_client.models.peer import Peer

class PeerDetailsResponseData(BaseModel):
    """
    PeerDetailsResponseData
    """
    peer: Peer = Field(...)
    token: StrictStr = Field(..., description="Token for authorizing websocket connection")
    __properties = ["peer", "token"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PeerDetailsResponseData:
        """Create an instance of PeerDetailsResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of peer
        if self.peer:
            _dict['peer'] = self.peer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PeerDetailsResponseData:
        """Create an instance of PeerDetailsResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PeerDetailsResponseData.parse_obj(obj)

        _obj = PeerDetailsResponseData.parse_obj({
            "peer": Peer.from_dict(obj.get("peer")) if obj.get("peer") is not None else None,
            "token": obj.get("token")
        })
        return _obj


