version: "3"

services:
  jellyfish:
    image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-edge}"
    container_name: jellyfish
    restart: on-failure
    healthcheck:
      test: >
        curl --fail -H "authorization: Bearer development" http://jellyfish:5002/room || exit 1
      interval: 3s
      retries: 2
      timeout: 2s
      start_period: 30s
    environment:
      JF_HOST: "jellyfish"
      JF_INTEGRATED_TURN_IP: "${INTEGRATED_TURN_IP:-127.0.0.1}"
      JF_INTEGRATED_TURN_LISTEN_IP: "0.0.0.0"
      JF_INTEGRATED_TURN_PORT_RANGE: "50000-50050"
      JF_INTEGRATED_TCP_TURN_PORT: "49999"
      JF_SERVER_API_TOKEN: "development"
      JF_PORT: 5002
      JF_SECRET_KEY_BASE: "super-secret-key"
      JF_SIP_USED: "true"
      JF_SIP_IP: "127.0.0.1"
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50050:50000-50050/udp"
    volumes:
      - ./tests/fixtures:/app/jellyfish_resources/file_component_sources

  test:
    container_name: test
    image: "cimg/python:${PYTHON_VERSION:-3.8}"
    command: sh -c "cd /app && \ poetry config virtualenvs.in-project false && \ poetry install --no-ansi && \ poetry run pytest -s"
    environment:
      DOCKER_TEST: "TRUE"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      jellyfish:
        condition: service_healthy

  examples:
    container_name: examples
    image: "cimg/python:${PYTHON_VERSION:-3.8}"
    command: sh -c "cd /app && \ poetry config virtualenvs.in-project false && \ poetry install --no-ansi && \ poetry run examples"
    environment:
      DOCKER_TEST: "TRUE"
      CI_LIMIT: "10"
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      jellyfish:
        condition: service_healthy
