site_name: Python Server SDK
use_directory_urls: false
# theme: simple-blog

plugins:
  - mike:
        # These fields are all optional; the defaults are as below...
        alias_type: symlink
        redirect_template: null
        deploy_prefix: ''
        canonical_version: null
        version_selector: true
        css_dir: css
        javascript_dir: js

theme: 
  name: mkdocs
  navigation_depth: 0

extra_javascript:
  - js/custom.js

extra_css:
  - css/custom.css