# coding: utf-8

"""
    Jellyfish Media Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.hls_skip import HlsSkip  # noqa: E501
from openapi_client.rest import ApiException

class TestHlsSkip(unittest.TestCase):
    """HlsSkip unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHlsSkip(self):
        """Test HlsSkip"""
        # inst = HlsSkip()

if __name__ == '__main__':
    unittest.main()
