# coding: utf-8

"""
    Jellyfish Media Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.add_peer_request import AddPeerRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestAddPeerRequest(unittest.TestCase):
    """AddPeerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AddPeerRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddPeerRequest`
        """
        model = openapi_client.models.add_peer_request.AddPeerRequest()  # noqa: E501
        if include_optional :
            return AddPeerRequest(
                options = openapi_client.models.peer_options.PeerOptions(), 
                type = 'webrtc'
            )
        else :
            return AddPeerRequest(
                options = openapi_client.models.peer_options.PeerOptions(),
                type = 'webrtc',
        )
        """

    def testAddPeerRequest(self):
        """Test AddPeerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
