# coding: utf-8

"""
    Jellyfish Media Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.room_api import RoomApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRoomApi(unittest.TestCase):
    """RoomApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.room_api.RoomApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_component(self):
        """Test case for add_component

        Creates the component and adds it to the room  # noqa: E501
        """
        pass

    def test_add_peer(self):
        """Test case for add_peer

        Create peer  # noqa: E501
        """
        pass

    def test_create_room(self):
        """Test case for create_room

        Creates a room  # noqa: E501
        """
        pass

    def test_delete_component(self):
        """Test case for delete_component

        Delete the component from the room  # noqa: E501
        """
        pass

    def test_delete_peer(self):
        """Test case for delete_peer

        Delete peer  # noqa: E501
        """
        pass

    def test_delete_room(self):
        """Test case for delete_room

        Delete the room  # noqa: E501
        """
        pass

    def test_get_all_rooms(self):
        """Test case for get_all_rooms

        Show information about all rooms  # noqa: E501
        """
        pass

    def test_get_room(self):
        """Test case for get_room

        Shows information about the room  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
