# coding: utf-8

"""
    Jellyfish Media Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.peer_details_response import PeerDetailsResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestPeerDetailsResponse(unittest.TestCase):
    """PeerDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PeerDetailsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeerDetailsResponse`
        """
        model = openapi_client.models.peer_details_response.PeerDetailsResponse()  # noqa: E501
        if include_optional :
            return PeerDetailsResponse(
                data = openapi_client.models.peer_details_response_data.PeerDetailsResponse_data(
                    peer = openapi_client.models.peer.Peer(
                        id = 'peer-1', 
                        status = 'disconnected', 
                        type = 'webrtc', ), 
                    token = '5cdac726-57a3-4ecb-b1d5-72a3d62ec242', )
            )
        else :
            return PeerDetailsResponse(
                data = openapi_client.models.peer_details_response_data.PeerDetailsResponse_data(
                    peer = openapi_client.models.peer.Peer(
                        id = 'peer-1', 
                        status = 'disconnected', 
                        type = 'webrtc', ), 
                    token = '5cdac726-57a3-4ecb-b1d5-72a3d62ec242', ),
        )
        """

    def testPeerDetailsResponse(self):
        """Test PeerDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
