# coding: utf-8

"""
    Jellyfish Media Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.rooms_listing_response import RoomsListingResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestRoomsListingResponse(unittest.TestCase):
    """RoomsListingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RoomsListingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoomsListingResponse`
        """
        model = openapi_client.models.rooms_listing_response.RoomsListingResponse()  # noqa: E501
        if include_optional :
            return RoomsListingResponse(
                data = [
                    openapi_client.models.room.Room(
                        components = [
                            openapi_client.models.component.Component(
                                id = 'component-1', 
                                metadata = openapi_client.models.component_metadata.ComponentMetadata(
                                    playable = True, ), 
                                type = 'hls', )
                            ], 
                        config = openapi_client.models.room_config.RoomConfig(
                            max_peers = 10, 
                            video_codec = 'h264', ), 
                        id = 'room-1', 
                        peers = [
                            openapi_client.models.peer.Peer(
                                id = 'peer-1', 
                                status = 'disconnected', 
                                type = 'webrtc', )
                            ], )
                    ]
            )
        else :
            return RoomsListingResponse(
                data = [
                    openapi_client.models.room.Room(
                        components = [
                            openapi_client.models.component.Component(
                                id = 'component-1', 
                                metadata = openapi_client.models.component_metadata.ComponentMetadata(
                                    playable = True, ), 
                                type = 'hls', )
                            ], 
                        config = openapi_client.models.room_config.RoomConfig(
                            max_peers = 10, 
                            video_codec = 'h264', ), 
                        id = 'room-1', 
                        peers = [
                            openapi_client.models.peer.Peer(
                                id = 'peer-1', 
                                status = 'disconnected', 
                                type = 'webrtc', )
                            ], )
                    ],
        )
        """

    def testRoomsListingResponse(self):
        """Test RoomsListingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
