version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Lint
          command: pylint --rcfile=pylintrc jellyfish tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build:
    jobs:
      - lint