version: 2.1

executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

jobs:
  lint:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: poetry install --no-ansi
      - run:
          name: Lint
          command: poetry run lint
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  test:
    executor: machine_executor_amd64
    steps:
      - checkout
      - run: docker compose -f docker-compose-test.yaml run test


workflows:
  build:
    jobs:
      - lint
      - test
