# coding: utf-8

"""
    Jellyfish Media Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import jellyfish_openapi_client
from jellyfish_openapi_client.models.room import Room  # noqa: E501
from jellyfish_openapi_client.rest import ApiException

class TestRoom(unittest.TestCase):
    """Room unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Room
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Room`
        """
        model = jellyfish_openapi_client.models.room.Room()  # noqa: E501
        if include_optional :
            return Room(
                components = [
                    jellyfish_openapi_client.models.component.Component(
                        id = 'component-1', 
                        metadata = jellyfish_openapi_client.models.component_metadata.ComponentMetadata(
                            playable = True, ), 
                        type = 'hls', )
                    ], 
                config = jellyfish_openapi_client.models.room_config.RoomConfig(
                    max_peers = 10, 
                    video_codec = 'h264', ), 
                id = 'room-1', 
                peers = [
                    jellyfish_openapi_client.models.peer.Peer(
                        id = 'peer-1', 
                        status = 'disconnected', 
                        type = 'webrtc', )
                    ]
            )
        else :
            return Room(
                components = [
                    jellyfish_openapi_client.models.component.Component(
                        id = 'component-1', 
                        metadata = jellyfish_openapi_client.models.component_metadata.ComponentMetadata(
                            playable = True, ), 
                        type = 'hls', )
                    ],
                config = jellyfish_openapi_client.models.room_config.RoomConfig(
                    max_peers = 10, 
                    video_codec = 'h264', ),
                id = 'room-1',
                peers = [
                    jellyfish_openapi_client.models.peer.Peer(
                        id = 'peer-1', 
                        status = 'disconnected', 
                        type = 'webrtc', )
                    ],
        )
        """

    def testRoom(self):
        """Test Room"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
