# coding: utf-8

"""
    Jellyfish Media Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import jellyfish_openapi_client
from jellyfish_openapi_client.models.peer_status import PeerStatus  # noqa: E501
from jellyfish_openapi_client.rest import ApiException

class TestPeerStatus(unittest.TestCase):
    """PeerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeerStatus(self):
        """Test PeerStatus"""
        # inst = PeerStatus()

if __name__ == '__main__':
    unittest.main()
