# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/jellyfish/peer_notifications.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)protos/jellyfish/peer_notifications.proto\x12\tjellyfish\"\x98\x02\n\x0bPeerMessage\x12=\n\rauthenticated\x18\x01 \x01(\x0b\x32$.jellyfish.PeerMessage.AuthenticatedH\x00\x12:\n\x0c\x61uth_request\x18\x02 \x01(\x0b\x32\".jellyfish.PeerMessage.AuthRequestH\x00\x12\x38\n\x0bmedia_event\x18\x03 \x01(\x0b\x32!.jellyfish.PeerMessage.MediaEventH\x00\x1a\x0f\n\rAuthenticated\x1a\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\x1a\x1a\n\nMediaEvent\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\tB\t\n\x07\x63ontentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'protos.jellyfish.peer_notifications_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_PEERMESSAGE']._serialized_start = 57
    _globals['_PEERMESSAGE']._serialized_end = 337
    _globals['_PEERMESSAGE_AUTHENTICATED']._serialized_start = 253
    _globals['_PEERMESSAGE_AUTHENTICATED']._serialized_end = 268
    _globals['_PEERMESSAGE_AUTHREQUEST']._serialized_start = 270
    _globals['_PEERMESSAGE_AUTHREQUEST']._serialized_end = 298
    _globals['_PEERMESSAGE_MEDIAEVENT']._serialized_start = 300
    _globals['_PEERMESSAGE_MEDIAEVENT']._serialized_end = 326
# @@protoc_insertion_point(module_scope)
