# coding: utf-8

"""
    Python API wrapper for Jellyfish Media Server

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PeerStatus(str, Enum):
    """
    Informs about the peer status
    """

    """
    allowed enum values
    """
    CONNECTED = 'connected'
    DISCONNECTED = 'disconnected'

    @classmethod
    def from_json(cls, json_str: str) -> PeerStatus:
        """Create an instance of PeerStatus from a JSON string"""
        return PeerStatus(json.loads(json_str))


