# coding: utf-8

"""
    Python API wrapper for Jellyfish Media Server

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from jellyfish._openapi_client.models.s3_credentials import S3Credentials
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

COMPONENTOPTIONSHLSS3_ONE_OF_SCHEMAS = ["S3Credentials"]


class ComponentOptionsHLSS3(BaseModel):
    """
    Credentials to AWS S3 bucket.
    """

    # data type: S3Credentials
    oneof_schema_1_validator: Optional[S3Credentials] = None
    if TYPE_CHECKING:
        actual_instance: Union[S3Credentials]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(COMPONENTOPTIONSHLSS3_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs):
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = ComponentOptionsHLSS3.construct()
        error_messages = []
        match = 0
        # validate data type: S3Credentials
        if not isinstance(v, S3Credentials):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `S3Credentials`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in ComponentOptionsHLSS3 with oneOf schemas: S3Credentials. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in ComponentOptionsHLSS3 with oneOf schemas: S3Credentials. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> ComponentOptionsHLSS3:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> ComponentOptionsHLSS3:
        """Returns the object represented by the json string"""
        instance = ComponentOptionsHLSS3.construct()
        if json_str is None:
            return instance

        error_messages = []
        match = 0

        # deserialize data into S3Credentials
        try:
            instance.actual_instance = S3Credentials.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into ComponentOptionsHLSS3 with oneOf schemas: S3Credentials. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into ComponentOptionsHLSS3 with oneOf schemas: S3Credentials. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())
