# coding: utf-8

"""
    Python API wrapper for Jellyfish Media Server

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, Field, StrictStr
from jellyfish._openapi_client.models.room import Room


class RoomCreateDetailsResponseData(BaseModel):
    """
    RoomCreateDetailsResponseData
    """

    jellyfish_address: StrictStr = Field(
        ...,
        description="Jellyfish instance address where the room was created. This might be different than the address of Jellyfish where the request was sent only when running a cluster of Jellyfishes.",
    )
    room: Room = Field(...)
    __properties = ["jellyfish_address", "room"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RoomCreateDetailsResponseData:
        """Create an instance of RoomCreateDetailsResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of room
        if self.room:
            _dict["room"] = self.room.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RoomCreateDetailsResponseData:
        """Create an instance of RoomCreateDetailsResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RoomCreateDetailsResponseData.parse_obj(obj)

        _obj = RoomCreateDetailsResponseData.parse_obj(
            {
                "jellyfish_address": obj.get("jellyfish_address"),
                "room": Room.from_dict(obj.get("room"))
                if obj.get("room") is not None
                else None,
            }
        )
        return _obj
