# coding: utf-8

"""
    Python API wrapper for Jellyfish Media Server

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist


class SubscriptionConfig(BaseModel):
    """
    Subscription config
    """

    tracks: Optional[conlist(StrictStr)] = Field(
        None, description="List of tracks that hls endpoint will subscribe for"
    )
    __properties = ["tracks"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SubscriptionConfig:
        """Create an instance of SubscriptionConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SubscriptionConfig:
        """Create an instance of SubscriptionConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SubscriptionConfig.parse_obj(obj)

        _obj = SubscriptionConfig.parse_obj({"tracks": obj.get("tracks")})
        return _obj
