# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protos/jellyfish/peer_notifications.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PeerMessage(betterproto.Message):
    authenticated: "PeerMessageAuthenticated" = betterproto.message_field(
        1, group="content"
    )
    auth_request: "PeerMessageAuthRequest" = betterproto.message_field(
        2, group="content"
    )
    media_event: "PeerMessageMediaEvent" = betterproto.message_field(3, group="content")


@dataclass
class PeerMessageAuthenticated(betterproto.Message):
    pass


@dataclass
class PeerMessageAuthRequest(betterproto.Message):
    token: str = betterproto.string_field(1)


@dataclass
class PeerMessageMediaEvent(betterproto.Message):
    data: str = betterproto.string_field(1)
